# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import variant_pb2 as variant__pb2


class VariantControllerStub(object):
    """import "google/protobuf/empty.proto";

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.List = channel.unary_stream(
                '/user.VariantController/List',
                request_serializer=variant__pb2.VariantListRequest.SerializeToString,
                response_deserializer=variant__pb2.Variant.FromString,
                )
        self.Create = channel.unary_unary(
                '/user.VariantController/Create',
                request_serializer=variant__pb2.Variant.SerializeToString,
                response_deserializer=variant__pb2.Variant.FromString,
                )
        self.Retrieve = channel.unary_unary(
                '/user.VariantController/Retrieve',
                request_serializer=variant__pb2.VariantRetrieveRequest.SerializeToString,
                response_deserializer=variant__pb2.Variant.FromString,
                )
        self.RetrieveParents = channel.unary_stream(
                '/user.VariantController/RetrieveParents',
                request_serializer=variant__pb2.VariantListRequest.SerializeToString,
                response_deserializer=variant__pb2.Variant.FromString,
                )
        self.RetrieveChilds = channel.unary_stream(
                '/user.VariantController/RetrieveChilds',
                request_serializer=variant__pb2.VariantRetrieveRequest.SerializeToString,
                response_deserializer=variant__pb2.Variant.FromString,
                )
        self.Update = channel.unary_unary(
                '/user.VariantController/Update',
                request_serializer=variant__pb2.Variant.SerializeToString,
                response_deserializer=variant__pb2.Variant.FromString,
                )
        self.Destroy = channel.unary_unary(
                '/user.VariantController/Destroy',
                request_serializer=variant__pb2.VariantDeleteRequest.SerializeToString,
                response_deserializer=variant__pb2.Variant.FromString,
                )


class VariantControllerServicer(object):
    """import "google/protobuf/empty.proto";

    """

    def List(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Create(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Retrieve(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RetrieveParents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RetrieveChilds(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Update(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Destroy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VariantControllerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'List': grpc.unary_stream_rpc_method_handler(
                    servicer.List,
                    request_deserializer=variant__pb2.VariantListRequest.FromString,
                    response_serializer=variant__pb2.Variant.SerializeToString,
            ),
            'Create': grpc.unary_unary_rpc_method_handler(
                    servicer.Create,
                    request_deserializer=variant__pb2.Variant.FromString,
                    response_serializer=variant__pb2.Variant.SerializeToString,
            ),
            'Retrieve': grpc.unary_unary_rpc_method_handler(
                    servicer.Retrieve,
                    request_deserializer=variant__pb2.VariantRetrieveRequest.FromString,
                    response_serializer=variant__pb2.Variant.SerializeToString,
            ),
            'RetrieveParents': grpc.unary_stream_rpc_method_handler(
                    servicer.RetrieveParents,
                    request_deserializer=variant__pb2.VariantListRequest.FromString,
                    response_serializer=variant__pb2.Variant.SerializeToString,
            ),
            'RetrieveChilds': grpc.unary_stream_rpc_method_handler(
                    servicer.RetrieveChilds,
                    request_deserializer=variant__pb2.VariantRetrieveRequest.FromString,
                    response_serializer=variant__pb2.Variant.SerializeToString,
            ),
            'Update': grpc.unary_unary_rpc_method_handler(
                    servicer.Update,
                    request_deserializer=variant__pb2.Variant.FromString,
                    response_serializer=variant__pb2.Variant.SerializeToString,
            ),
            'Destroy': grpc.unary_unary_rpc_method_handler(
                    servicer.Destroy,
                    request_deserializer=variant__pb2.VariantDeleteRequest.FromString,
                    response_serializer=variant__pb2.Variant.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'user.VariantController', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class VariantController(object):
    """import "google/protobuf/empty.proto";

    """

    @staticmethod
    def List(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/user.VariantController/List',
            variant__pb2.VariantListRequest.SerializeToString,
            variant__pb2.Variant.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Create(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/user.VariantController/Create',
            variant__pb2.Variant.SerializeToString,
            variant__pb2.Variant.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Retrieve(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/user.VariantController/Retrieve',
            variant__pb2.VariantRetrieveRequest.SerializeToString,
            variant__pb2.Variant.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RetrieveParents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/user.VariantController/RetrieveParents',
            variant__pb2.VariantListRequest.SerializeToString,
            variant__pb2.Variant.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RetrieveChilds(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/user.VariantController/RetrieveChilds',
            variant__pb2.VariantRetrieveRequest.SerializeToString,
            variant__pb2.Variant.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Update(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/user.VariantController/Update',
            variant__pb2.Variant.SerializeToString,
            variant__pb2.Variant.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Destroy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/user.VariantController/Destroy',
            variant__pb2.VariantDeleteRequest.SerializeToString,
            variant__pb2.Variant.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class VariantOptionControllerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.List = channel.unary_stream(
                '/user.VariantOptionController/List',
                request_serializer=variant__pb2.OptionListRequest.SerializeToString,
                response_deserializer=variant__pb2.VariantOption.FromString,
                )
        self.VariantOptionList = channel.unary_stream(
                '/user.VariantOptionController/VariantOptionList',
                request_serializer=variant__pb2.VariantOptionListRequest.SerializeToString,
                response_deserializer=variant__pb2.VariantOption.FromString,
                )
        self.Create = channel.unary_unary(
                '/user.VariantOptionController/Create',
                request_serializer=variant__pb2.VariantOption.SerializeToString,
                response_deserializer=variant__pb2.VariantOption.FromString,
                )
        self.Retrieve = channel.unary_unary(
                '/user.VariantOptionController/Retrieve',
                request_serializer=variant__pb2.VariantOptionRetrieveRequest.SerializeToString,
                response_deserializer=variant__pb2.VariantOption.FromString,
                )
        self.Update = channel.unary_unary(
                '/user.VariantOptionController/Update',
                request_serializer=variant__pb2.VariantOption.SerializeToString,
                response_deserializer=variant__pb2.VariantOption.FromString,
                )
        self.Destroy = channel.unary_unary(
                '/user.VariantOptionController/Destroy',
                request_serializer=variant__pb2.VariantOption.SerializeToString,
                response_deserializer=variant__pb2.VariantOption.FromString,
                )


class VariantOptionControllerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def List(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VariantOptionList(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Create(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Retrieve(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Update(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Destroy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VariantOptionControllerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'List': grpc.unary_stream_rpc_method_handler(
                    servicer.List,
                    request_deserializer=variant__pb2.OptionListRequest.FromString,
                    response_serializer=variant__pb2.VariantOption.SerializeToString,
            ),
            'VariantOptionList': grpc.unary_stream_rpc_method_handler(
                    servicer.VariantOptionList,
                    request_deserializer=variant__pb2.VariantOptionListRequest.FromString,
                    response_serializer=variant__pb2.VariantOption.SerializeToString,
            ),
            'Create': grpc.unary_unary_rpc_method_handler(
                    servicer.Create,
                    request_deserializer=variant__pb2.VariantOption.FromString,
                    response_serializer=variant__pb2.VariantOption.SerializeToString,
            ),
            'Retrieve': grpc.unary_unary_rpc_method_handler(
                    servicer.Retrieve,
                    request_deserializer=variant__pb2.VariantOptionRetrieveRequest.FromString,
                    response_serializer=variant__pb2.VariantOption.SerializeToString,
            ),
            'Update': grpc.unary_unary_rpc_method_handler(
                    servicer.Update,
                    request_deserializer=variant__pb2.VariantOption.FromString,
                    response_serializer=variant__pb2.VariantOption.SerializeToString,
            ),
            'Destroy': grpc.unary_unary_rpc_method_handler(
                    servicer.Destroy,
                    request_deserializer=variant__pb2.VariantOption.FromString,
                    response_serializer=variant__pb2.VariantOption.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'user.VariantOptionController', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class VariantOptionController(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def List(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/user.VariantOptionController/List',
            variant__pb2.OptionListRequest.SerializeToString,
            variant__pb2.VariantOption.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def VariantOptionList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/user.VariantOptionController/VariantOptionList',
            variant__pb2.VariantOptionListRequest.SerializeToString,
            variant__pb2.VariantOption.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Create(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/user.VariantOptionController/Create',
            variant__pb2.VariantOption.SerializeToString,
            variant__pb2.VariantOption.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Retrieve(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/user.VariantOptionController/Retrieve',
            variant__pb2.VariantOptionRetrieveRequest.SerializeToString,
            variant__pb2.VariantOption.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Update(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/user.VariantOptionController/Update',
            variant__pb2.VariantOption.SerializeToString,
            variant__pb2.VariantOption.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Destroy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/user.VariantOptionController/Destroy',
            variant__pb2.VariantOption.SerializeToString,
            variant__pb2.VariantOption.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
