# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import attribute_pb2 as attribute__pb2


class AttributeControllerStub(object):
    """import "google/protobuf/empty.proto";

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.List = channel.unary_stream(
                '/user.AttributeController/List',
                request_serializer=attribute__pb2.AttributeListRequest.SerializeToString,
                response_deserializer=attribute__pb2.Attribute.FromString,
                )
        self.Create = channel.unary_unary(
                '/user.AttributeController/Create',
                request_serializer=attribute__pb2.Attribute.SerializeToString,
                response_deserializer=attribute__pb2.Attribute.FromString,
                )
        self.Retrieve = channel.unary_unary(
                '/user.AttributeController/Retrieve',
                request_serializer=attribute__pb2.AttributeRetrieveRequest.SerializeToString,
                response_deserializer=attribute__pb2.Attribute.FromString,
                )
        self.RetrieveParents = channel.unary_stream(
                '/user.AttributeController/RetrieveParents',
                request_serializer=attribute__pb2.AttributeListRequest.SerializeToString,
                response_deserializer=attribute__pb2.Attribute.FromString,
                )
        self.RetrieveChilds = channel.unary_stream(
                '/user.AttributeController/RetrieveChilds',
                request_serializer=attribute__pb2.AttributeRetrieveRequest.SerializeToString,
                response_deserializer=attribute__pb2.Attribute.FromString,
                )
        self.Update = channel.unary_unary(
                '/user.AttributeController/Update',
                request_serializer=attribute__pb2.Attribute.SerializeToString,
                response_deserializer=attribute__pb2.Attribute.FromString,
                )
        self.Destroy = channel.unary_unary(
                '/user.AttributeController/Destroy',
                request_serializer=attribute__pb2.AttributeDeleteRequest.SerializeToString,
                response_deserializer=attribute__pb2.Attribute.FromString,
                )


class AttributeControllerServicer(object):
    """import "google/protobuf/empty.proto";

    """

    def List(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Create(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Retrieve(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RetrieveParents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RetrieveChilds(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Update(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Destroy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AttributeControllerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'List': grpc.unary_stream_rpc_method_handler(
                    servicer.List,
                    request_deserializer=attribute__pb2.AttributeListRequest.FromString,
                    response_serializer=attribute__pb2.Attribute.SerializeToString,
            ),
            'Create': grpc.unary_unary_rpc_method_handler(
                    servicer.Create,
                    request_deserializer=attribute__pb2.Attribute.FromString,
                    response_serializer=attribute__pb2.Attribute.SerializeToString,
            ),
            'Retrieve': grpc.unary_unary_rpc_method_handler(
                    servicer.Retrieve,
                    request_deserializer=attribute__pb2.AttributeRetrieveRequest.FromString,
                    response_serializer=attribute__pb2.Attribute.SerializeToString,
            ),
            'RetrieveParents': grpc.unary_stream_rpc_method_handler(
                    servicer.RetrieveParents,
                    request_deserializer=attribute__pb2.AttributeListRequest.FromString,
                    response_serializer=attribute__pb2.Attribute.SerializeToString,
            ),
            'RetrieveChilds': grpc.unary_stream_rpc_method_handler(
                    servicer.RetrieveChilds,
                    request_deserializer=attribute__pb2.AttributeRetrieveRequest.FromString,
                    response_serializer=attribute__pb2.Attribute.SerializeToString,
            ),
            'Update': grpc.unary_unary_rpc_method_handler(
                    servicer.Update,
                    request_deserializer=attribute__pb2.Attribute.FromString,
                    response_serializer=attribute__pb2.Attribute.SerializeToString,
            ),
            'Destroy': grpc.unary_unary_rpc_method_handler(
                    servicer.Destroy,
                    request_deserializer=attribute__pb2.AttributeDeleteRequest.FromString,
                    response_serializer=attribute__pb2.Attribute.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'user.AttributeController', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AttributeController(object):
    """import "google/protobuf/empty.proto";

    """

    @staticmethod
    def List(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/user.AttributeController/List',
            attribute__pb2.AttributeListRequest.SerializeToString,
            attribute__pb2.Attribute.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Create(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/user.AttributeController/Create',
            attribute__pb2.Attribute.SerializeToString,
            attribute__pb2.Attribute.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Retrieve(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/user.AttributeController/Retrieve',
            attribute__pb2.AttributeRetrieveRequest.SerializeToString,
            attribute__pb2.Attribute.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RetrieveParents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/user.AttributeController/RetrieveParents',
            attribute__pb2.AttributeListRequest.SerializeToString,
            attribute__pb2.Attribute.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RetrieveChilds(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/user.AttributeController/RetrieveChilds',
            attribute__pb2.AttributeRetrieveRequest.SerializeToString,
            attribute__pb2.Attribute.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Update(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/user.AttributeController/Update',
            attribute__pb2.Attribute.SerializeToString,
            attribute__pb2.Attribute.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Destroy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/user.AttributeController/Destroy',
            attribute__pb2.AttributeDeleteRequest.SerializeToString,
            attribute__pb2.Attribute.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class AttributeOptionControllerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.List = channel.unary_stream(
                '/user.AttributeOptionController/List',
                request_serializer=attribute__pb2.OptionsListRequest.SerializeToString,
                response_deserializer=attribute__pb2.AttributeOption.FromString,
                )
        self.AttributeOptionList = channel.unary_stream(
                '/user.AttributeOptionController/AttributeOptionList',
                request_serializer=attribute__pb2.AttributeOptionListRequest.SerializeToString,
                response_deserializer=attribute__pb2.AttributeOption.FromString,
                )
        self.Create = channel.unary_unary(
                '/user.AttributeOptionController/Create',
                request_serializer=attribute__pb2.AttributeOption.SerializeToString,
                response_deserializer=attribute__pb2.AttributeOption.FromString,
                )
        self.Retrieve = channel.unary_unary(
                '/user.AttributeOptionController/Retrieve',
                request_serializer=attribute__pb2.AttributeOptionRetrieveRequest.SerializeToString,
                response_deserializer=attribute__pb2.AttributeOption.FromString,
                )
        self.Update = channel.unary_unary(
                '/user.AttributeOptionController/Update',
                request_serializer=attribute__pb2.AttributeOption.SerializeToString,
                response_deserializer=attribute__pb2.AttributeOption.FromString,
                )
        self.Destroy = channel.unary_unary(
                '/user.AttributeOptionController/Destroy',
                request_serializer=attribute__pb2.AttributeOption.SerializeToString,
                response_deserializer=attribute__pb2.AttributeOption.FromString,
                )


class AttributeOptionControllerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def List(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AttributeOptionList(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Create(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Retrieve(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Update(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Destroy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AttributeOptionControllerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'List': grpc.unary_stream_rpc_method_handler(
                    servicer.List,
                    request_deserializer=attribute__pb2.OptionsListRequest.FromString,
                    response_serializer=attribute__pb2.AttributeOption.SerializeToString,
            ),
            'AttributeOptionList': grpc.unary_stream_rpc_method_handler(
                    servicer.AttributeOptionList,
                    request_deserializer=attribute__pb2.AttributeOptionListRequest.FromString,
                    response_serializer=attribute__pb2.AttributeOption.SerializeToString,
            ),
            'Create': grpc.unary_unary_rpc_method_handler(
                    servicer.Create,
                    request_deserializer=attribute__pb2.AttributeOption.FromString,
                    response_serializer=attribute__pb2.AttributeOption.SerializeToString,
            ),
            'Retrieve': grpc.unary_unary_rpc_method_handler(
                    servicer.Retrieve,
                    request_deserializer=attribute__pb2.AttributeOptionRetrieveRequest.FromString,
                    response_serializer=attribute__pb2.AttributeOption.SerializeToString,
            ),
            'Update': grpc.unary_unary_rpc_method_handler(
                    servicer.Update,
                    request_deserializer=attribute__pb2.AttributeOption.FromString,
                    response_serializer=attribute__pb2.AttributeOption.SerializeToString,
            ),
            'Destroy': grpc.unary_unary_rpc_method_handler(
                    servicer.Destroy,
                    request_deserializer=attribute__pb2.AttributeOption.FromString,
                    response_serializer=attribute__pb2.AttributeOption.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'user.AttributeOptionController', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AttributeOptionController(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def List(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/user.AttributeOptionController/List',
            attribute__pb2.OptionsListRequest.SerializeToString,
            attribute__pb2.AttributeOption.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AttributeOptionList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/user.AttributeOptionController/AttributeOptionList',
            attribute__pb2.AttributeOptionListRequest.SerializeToString,
            attribute__pb2.AttributeOption.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Create(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/user.AttributeOptionController/Create',
            attribute__pb2.AttributeOption.SerializeToString,
            attribute__pb2.AttributeOption.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Retrieve(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/user.AttributeOptionController/Retrieve',
            attribute__pb2.AttributeOptionRetrieveRequest.SerializeToString,
            attribute__pb2.AttributeOption.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Update(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/user.AttributeOptionController/Update',
            attribute__pb2.AttributeOption.SerializeToString,
            attribute__pb2.AttributeOption.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Destroy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/user.AttributeOptionController/Destroy',
            attribute__pb2.AttributeOption.SerializeToString,
            attribute__pb2.AttributeOption.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
